import pygame
import time

FPS = 50
HEAT_POINT_COUNT = 3

pygame.mixer.init()
pygame.font.init()
size = width, height = 1000, 800
clock = pygame.time.Clock()
screen = pygame.display.set_mode(size)


def show_go_screen():
    screen.fill((0, 0, 0))
    pygame.display.flip()
    time.sleep(1)
    bg = pygame.image.load("Финальное окно 2 кадр.png")
    screen.blit(bg, (0, 0))
    pygame.display.flip()
    time.sleep(1)
    screen.fill((0, 0, 0))
    pygame.display.flip()
    time.sleep(1)
    bg = pygame.image.load("Финальное окно 3 кадр.png")
    screen.blit(bg, (0, 0))
    pygame.display.flip()
    time.sleep(1)
    screen.fill((0, 0, 0))
    pygame.display.flip()
    time.sleep(1)
    bg = pygame.image.load("Финальное окно кадр 4.png")
    screen.blit(bg, (0, 0))
    pygame.display.flip()
    time.sleep(1)
    screen.fill((0, 0, 0))
    pygame.display.flip()
    time.sleep(1)
    bg = pygame.image.load("Финальное окно кадр 5.png")
    screen.blit(bg, (0, 0))
    pygame.display.flip()
    time.sleep(1)
    screen.blit(bg, (0, 0))
    pygame.display.flip()
    sound = pygame.mixer.Sound('gimn.wav')
    sound.play()

    waiting = True
    while waiting:
        clock.tick(FPS)
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
            if event.type == pygame.KEYUP:
                waiting = False
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-01.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-02.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-03.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-04.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-05.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-06.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-07.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-08.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-09.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-10.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-11.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-12.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 90)
        text = font.render(f"ПОТРАЧЕНО {HEAT_POINT_COUNT} HP", True, [255, 255, 255])
        screen.blit(text, (250, 650))
        bg = pygame.image.load("flag_animation/frame-13.gif")
        screen.blit(bg, (250, 276))
        pygame.display.flip()
        time.sleep(0.3)


show_go_screen()
